classifier_type: "avgpooling_patch_reps"
dropout: 0.1
patch_size: 200
by_subject: false
by_subject_inference: true
alignment_type: "adaptive_batch_norm"


encoders:
  task:
    name: "task"
    enabled: true

loss_config_stage1:
  classification: true
  classification_weight: 1.0
