# config_diva.yaml
classifier_type: "avgpooling_patch_reps"
dropout: 0.1
patch_size: 200
kernel_sizes: [3, 3, 3, 3]
pool_filter_size: 2
use_skip: True

encoders:
  task:
    name: "task"
    enabled: true
    # num_classes lo lasceremo vuoto qui per sovrascriverlo dinamicamente in Python
  # subject:
  #   name: "subject"
  #   enabled: true
  # noise:
  #   name: "noise"
  #   enabled: true

loss_config_stage1:
  classification: true
  classification_weight: 1.0

loss_config_stage2:
  classification: true
  classification_weight: 0.5