# Test Mode B
uv run ../dvae.py \
  --backbone 'cbramod' \
  --backbone-weights '/home/user/projects/eeg_disentanglement/data/weights/cbramod_pretrained_weights.pth' \
  --data-file '/home/user/projects/eeg_disentanglement/data/processed_data/clare_processed_thresh_5_cbramod.pt' \
  --epochs 200 \
  --batch-size 256 \
  --save-dir ../experiments/CLARE/CLARE_weighted_bands_5thresh_42_weakerKL_newgammaweighting \
  --lr 0.0001 \
  --stage1-epochs 0 \
  --run-name 'CLARE_weighted_bands_5thresh_42_weakerKL_newgammaweighting' \
  --use-wandb \
  --project-name "CLARE_CBraMod" \
  --loss-kl-weight 0.0001 \
  --loss-noise-kl-weight 0.00001 \
  --loss-class-weight 0.8 \
  --loss-var-class-weight 1.0 \
  --loss-intra-weight 0.5 \
  --loss-cross-class-weight 0.5 \
  --loss-kd-weight 0.1 \
  --mid_channels 4 2\